version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: tla-epb-timescaledb-1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./imports_measure:/imports_measure
      - ./imports_xfmr:/imports_xfmr
    environment:
      - POSTGRES_PASSWORD=epbPass
      - POSTGRES_USER=epb
      - POSTGRES_DB=xfmrdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U epb -d xfmrdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tla-epb-app-1
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./imports_measure:/imports_measure
      - ./imports_xfmr:/imports_xfmr
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://epb:epbPass@timescaledb:5432/xfmrdb
      # FORMAT
      # POSTGRESQL://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE>

volumes:
  timescaledb_data:
    driver: local
