-- CreateTable
CREATE TABLE "XfmrDimension" (
    "XFMR_SID" BIGINT NOT NULL,
    "EFFECTIVE_START_DATE" TIMESTAMP(3) NOT NULL,
    "EFFECTIVE_END_DATE" TIMESTAMP(3),
    "UPDATE_DATE" TIMESTAMP(3) NOT NULL,
    "CURRENT_INDICATOR" VARCHAR(10) NOT NULL,
    "GIS_BANK_INDICATOR" BIGINT NOT NULL,
    "GIS_IDENTIFIER" BIGINT NOT NULL,
    "XFMR_NUMBER" VARCHAR(50) NOT NULL,
    "KVA_RATING" VARCHAR(50) NOT NULL,
    "PHASE" VARCHAR(50) NOT NULL,

    CONSTRAINT "XfmrDimension_pkey" PRIMARY KEY ("XFMR_SID")
);

-- CreateTable
CREATE TABLE "XfmrDriverProfile" (
    "ID" SERIAL NOT NULL,
    "NAME" VARCHAR(20) NOT NULL,
    "MILES_DRIVEN" INTEGER NOT NULL,
    "KWH_EXPENDITURE" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "TIME_INTERVAL" INTEGER NOT NULL,

    CONSTRAINT "XfmrDriverProfile_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "XfmrMaxMeasures" (
    "XFMR_SID" BIGINT NOT NULL,
    "KVA_RATING" VARCHAR(50) NOT NULL,
    "KVA_MEASURE" DOUBLE PRECISION,

    CONSTRAINT "XfmrMaxMeasures_pkey" PRIMARY KEY ("XFMR_SID")
);

-- CreateTable
CREATE TABLE "XfmrMeasure" (
    "MEASURE_DATE" TIMESTAMP(3) NOT NULL,
    "UTC_TIME" TIMESTAMP(3) NOT NULL,
    "XFMR_SID" BIGINT NOT NULL,
    "SINGLE_PHASE" INTEGER,
    "POLY_PHASE" INTEGER,
    "SINGLE_PHASE_IN_LOAD" INTEGER,
    "POLY_PHASE_IN_LOAD" INTEGER,
    "KW_MEASURE" DOUBLE PRECISION,
    "KVA_MEASURE" DOUBLE PRECISION,
    "ID" SERIAL NOT NULL,

    CONSTRAINT "XfmrMeasure_pkey" PRIMARY KEY ("ID","MEASURE_DATE")
);

-- CreateTable
CREATE TABLE "XfmrTimeInterval" (
    "ID" SERIAL NOT NULL,
    "Start" TIME(6) NOT NULL,
    "End" TIME(6) NOT NULL,
    "Name" VARCHAR(20) NOT NULL,

    CONSTRAINT "XfmrTimeInterval_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "XfmrDimension_GIS_IDENTIFIER_idx" ON "XfmrDimension"("GIS_IDENTIFIER" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "XfmrDimension_XFMR_SID_key" ON "XfmrDimension"("XFMR_SID" ASC);

-- CreateIndex
CREATE INDEX "XfmrMaxMeasures_KVA_RATING_idx" ON "XfmrMaxMeasures"("KVA_RATING" ASC);

-- CreateIndex
CREATE INDEX "XfmrMeasure_MEASURE_DATE_UTC_TIME_idx" ON "XfmrMeasure"("MEASURE_DATE" ASC, "UTC_TIME" ASC);

-- CreateIndex
CREATE INDEX "XfmrMeasure_XFMR_SID_idx" ON "XfmrMeasure"("XFMR_SID" ASC);

-- CreateIndex
CREATE INDEX "idx_measure_date" ON "XfmrMeasure"("MEASURE_DATE" ASC);

-- AddForeignKey
ALTER TABLE "XfmrDriverProfile" ADD CONSTRAINT "XfmrDriverProfile_TIME_INTERVAL_fkey" FOREIGN KEY ("TIME_INTERVAL") REFERENCES "XfmrTimeInterval"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "XfmrMaxMeasures" ADD CONSTRAINT "XfmrMaxMeasures_XFMR_SID_fkey" FOREIGN KEY ("XFMR_SID") REFERENCES "XfmrDimension"("XFMR_SID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "XfmrMeasure" ADD CONSTRAINT "XfmrMeasure_XFMR_SID_fkey" FOREIGN KEY ("XFMR_SID") REFERENCES "XfmrDimension"("XFMR_SID") ON DELETE RESTRICT ON UPDATE CASCADE;



-- CREATE HYPERTABLE
SELECT create_hypertable('public."XfmrMeasure"', 'MEASURE_DATE');