-- CreateTable
CREATE TABLE "XfmrDimension" (
    "XFMR_SID" BIGINT NOT NULL,
    "EFFECTIVE_START_DATE" TIMESTAMP(3) NOT NULL,
    "EFFECTIVE_END_DATE" TIMESTAMP(3),
    "UPDATE_DATE" TIMESTAMP(3) NOT NULL,
    "CURRENT_INDICATOR" VARCHAR(2) NOT NULL,
    "GIS_BANK_INDICATOR" BIGINT NOT NULL,
    "GIS_IDENTIFIER" BIGINT NOT NULL,
    "XFMR_NUMBER" VARCHAR(50) NOT NULL,
    "KVA_RATING" VARCHAR(50) NOT NULL,
    "PHASE" VARCHAR(50) NOT NULL,

    CONSTRAINT "XfmrDimension_pkey" PRIMARY KEY ("XFMR_SID")
);

-- CreateTable
CREATE TABLE "XfmrMaxMeasures" (
    "XFMR_SID" BIGINT NOT NULL,
    "KVA_RATING" VARCHAR(50) NOT NULL,
    "KVA_MEASURE" DOUBLE PRECISION,

    CONSTRAINT "XfmrMaxMeasures_pkey" PRIMARY KEY ("XFMR_SID")
);

-- CreateTable
CREATE TABLE "XfmrMeasure" (
    "MEASURE_DATE" TIMESTAMP(3) NOT NULL,
    "UTC_TIME" TIMESTAMP(3) NOT NULL,
    "XFMR_SID" BIGINT NOT NULL,
    "SINGLE_PHASE" INTEGER,
    "POLY_PHASE" INTEGER,
    "SINGLE_PHASE_IN_LOAD" INTEGER,
    "POLY_PHASE_IN_LOAD" INTEGER,
    "KW_MEASURE" DOUBLE PRECISION,
    "KVA_MEASURE" DOUBLE PRECISION,

    CONSTRAINT "XfmrMeasure_pkey" PRIMARY KEY ("MEASURE_DATE")
);

-- CreateTable
CREATE TABLE "XfmrDriverProfile" (
    "ID" SERIAL NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "MILES_DRIVEN" INTEGER NOT NULL,
    "KVA_EXPENDITURE" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "XfmrDriverProfile_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "XfmrDimension_XFMR_SID_key" ON "XfmrDimension"("XFMR_SID");

-- CreateIndex
CREATE INDEX "XfmrDimension_GIS_IDENTIFIER_idx" ON "XfmrDimension"("GIS_IDENTIFIER");

-- CreateIndex
CREATE INDEX "XfmrMaxMeasures_KVA_RATING_idx" ON "XfmrMaxMeasures"("KVA_RATING");

-- CreateIndex
CREATE INDEX "XfmrMeasure_MEASURE_DATE_UTC_TIME_idx" ON "XfmrMeasure"("MEASURE_DATE", "UTC_TIME");

-- AddForeignKey
ALTER TABLE "XfmrMaxMeasures" ADD CONSTRAINT "XfmrMaxMeasures_XFMR_SID_fkey" FOREIGN KEY ("XFMR_SID") REFERENCES "XfmrDimension"("XFMR_SID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "XfmrMeasure" ADD CONSTRAINT "XfmrMeasure_XFMR_SID_fkey" FOREIGN KEY ("XFMR_SID") REFERENCES "XfmrDimension"("XFMR_SID") ON DELETE RESTRICT ON UPDATE CASCADE;
